@startuml
class Encoder {
    +encode(n: int): str
    +decode(short_code: str): int
}

class Storage {
    +get_short_code(full_url: str): str
    +get_full_url(short_code: str): str
}

class Service {
    +get_short_code(full_url: str): str
    +get_full_url(short_code: str): str
}

class HTTP_API {
    +process_request(request)
}

HTTP_API --> Service : запрос создания/получения ссылки
Service --> Storage : использует для поиска и сохранения
Storage --> Encoder : кодирует/декодирует идентификаторы
@enduml